### ISSUE TITLE
on infinite loading it takes sometimes 3-5 seconds for images to appear

### ISSUE THREAD

**Issue by nikocraft** [shershen08/vue-masonry#70] opened 2018-07-31 19:17 UTC
I've implemented infinite loading with this plugin and as I scroll down I load new images. All the images are already cached by the browser so browser is not waisting time loading them again but I can get a delay of 3-5 seconds before any action happens on screen. This can lead to user thinking that there are no more images and UI will feel unresponsive to user.

here is a video that demonstrates it:
https://www.youtube.com/watch?v=o9bs1zdMWIo

Notice sometimes the exact same page that is loaded that contains same images can load faster, but most of the time there is delay. If there is no delay when page it self is reloaded and images appear instantly why is there delay when I get a bunch of new images from server and I insert them into image array?

**Comment by shershen08** [comment] 2018-08-03 15:51
thanks for bringing it up @nikocraft 

On the video it's clearly visible the delay between the scroll action and images being shown. 
With this amount of images as in the demo I can't imagine this to be a delay due to some updates in the library. seems more like a delay of all images being shown until the last image in the list is loaded.

To debug this would be nice to have a reproduced issue in code demo. 
Is that possible, using jsfiddle or codepen maybe?

**Comment by nikocraft** [comment] 2018-08-03 15:52
I should add that we found out that this only happens on chrome and not on any other browser. I will see what I can do about reproducing it as a demo, need some time for that :)

**Comment by shershen08** [comment] 2018-10-30 14:34
any updates on that one @nikocraft  ?

**Comment by nikocraft** [comment] 2018-10-30 16:07
Yeah we fixed it we got baby smooth infinite scrolling now

**Comment by nikocraft** [comment] 2018-10-30 16:08
problem was solved with web-workers, it was the only way to get smooth animation :)

**Comment by shershen08** [comment] 2018-10-30 16:16
closing it then

**Closed by shershen08** 2018-10-30 16:16 UTC
