### ISSUE TITLE
Destroy masonry on unbind

### ISSUE THREAD

**Issue by MateuszPaulski** [shershen08/vue-masonry#48] opened 2017-12-13 11:12 UTC
Hi
I think there is a problem with resize events not being removed after directive unbind. Its creating new resize event every page view. I fixed it by adding another event that is fired in unbind method.
```
inserted: function (el, nodeObj) {
       ....
      Events.$on(EVENT_DESTROY, function (eventData) {
        masonry.destroy()
      })
    },
    unbind: function (el, nodeObj) {
      Events.$emit(EVENT_DESTROY)    
    }
```

**Comment by shershen08** [comment] 2017-12-13 18:11
thanks for the input @MateuszPaulski 
I'll take a look at this issue. if you have some demo code to reproduce - would be great.

**Comment by shershen08** [comment] 2017-12-21 19:05
I've created a branch with your fix @MateuszPaulski 
https://github.com/shershen08/vue-masonry/tree/fix/39-remove-bundled-vue
can you have a quick look ?

**Comment by kotuck** [comment] 2018-03-19 02:34
Hello, I have a problem with this code.  Can you choose one method to destroy component, please. 
I use Nuxt and when user click to router link that what he sees: masonry off (images still showing,in a column), delay ~100ms, then router changes. 
I deleted one (unbind) now everything works correctly.

**Comment by shershen08** [comment] 2018-03-19 09:11
can you please post more details, code snippet maybe which block produces problems.
creating a branch + PR would be even better

**Comment by Hadrien-DELAITRE** [comment] 2018-04-04 16:37
Hello @shershen08,

I opened a PR https://github.com/shershen08/vue-masonry/pull/57 to solve performance issues about event listeners. It's a memory leak especially when component is mounted several times (e.g. in an SPA environment)

**Comment by shershen08** [comment] 2018-04-06 08:32
Thanks for your time @Hadrien-DELAITRE

**Comment by kotuck** [comment] 2018-06-28 10:32
Hello, @shershen08! I'm sorry that I did not answer for so long. Why are you use masonry.destroy() function in masonry.plugin.js? It destroys the grid right before moving to another page. Could you remove this?
You can see how it works here. https://masonry.desandro.com/methods.html#destroy

**Comment by shershen08** [comment] 2018-10-30 14:33
@kotuck 
I don't quite understand motivation behind your proposal 

> It destroys the grid right before moving to another page. Could you remove this?

**Closed by shershen08** 2018-10-30 14:33 UTC
Labels: bug

**Comment by treardon17** [comment] 2018-12-16 19:43
@shershen08 I believe @kotuck may be referring to the grid being destroyed (visibly) before a Vue page transition completes? I'm currently having that problem and I would love a solution. I'm attempting to fade to the next page in my Vue application, but the masonry grid flickers and disappears before the page transition completes. Do you have any thoughts or recommendations?

**Comment by max-schu** [comment] 2019-03-18 14:08
> @kotuck
> I don't quite understand motivation behind your proposal
> 
> > It destroys the grid right before moving to another page. Could you remove this?

+1 why is this behaviour intended?

**Comment by mklasinc** [comment] 2019-09-20 08:45
> > @kotuck
> > I don't quite understand motivation behind your proposal
> > > It destroys the grid right before moving to another page. Could you remove this?
> 
> +1 why is this behaviour intended?

+1 having the same issue
